# This file was generated by GoReleaser. DO NOT EDIT.
class Gommit < Formula
  desc ""
  homepage ""
  version "2.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/antham/gommit/releases/download/v2.4.0/gommit_2.4.0_darwin_amd64.tar.gz"
    sha256 "5fc1d24859011ba51b862766c2d714b9beb32e7cf08da71aedacad72fc84dae9"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/antham/gommit/releases/download/v2.4.0/gommit_2.4.0_linux_amd64.tar.gz"
      sha256 "658c6b36661f058a82821da58cabc199579f38f04799e694366ca7bbd8196217"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/antham/gommit/releases/download/v2.4.0/gommit_2.4.0_linux_arm64.tar.gz"
        sha256 "7a6253e4b8e89d2e9506339a8fe24b1d15180dcd46d62bb46ab4ca439dcfd35d"
      else
        url "https://github.com/antham/gommit/releases/download/v2.4.0/gommit_2.4.0_linux_armv6.tar.gz"
        sha256 "c123f721025aecd9fa46085ded55484a9fe6738862f05484237a096a959862e7"
      end
    end
  end

  def install
    bin.install "gommit"
  end
end
